sonar.projectKey=safreu_hypr-restore_04b7dc96-e38d-4043-ba33-5c7891f8bfa7

sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=.

# Rust-Erkennung & Cargo
sonar.language=rust
sonar.rust.cargo.manifestPaths=Cargo.toml

# Reports (optional, falls vorhanden)
sonar.rust.clippy.reportPaths=clippy-report.json
sonar.coverageReportPaths=tarpaulin-report.xml

# Artefakte ignorieren
sonar.exclusions=**/target/**
