sonar.projectKey=safreu_hypr-restore_04b7dc96-e38d-4043-ba33-5c7891f8bfa7
sonar.sources=src
sonar.language=rust
sonar.rust.clippy.enabled=true
sonar.rust.clippy.reportPaths=clippy-report.json
sonar.rust.cargo.manifestPaths=Cargo.toml
