[package]
name = "hypr-restore"
version = "0.1.0"
edition = "2024"
authors = ["Samuel Freundel"]
license = "MIT"
repository = "https://github.com/safreu/hypr-restore"
description = "A tool to restore opened applications for hyprland"
keywords = ["hyprland", "backup", "restore", "event-listener", "tracker"]
categories = ["command-line-utilities"]
readme = "../readme.md"

[[bin]]
name = "hypr-restore"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.52", features = ["derive"] }
restore = { path = "../restore" }
listener = { path = "../listener" }
snapshot = { path = "../snapshot" }
dirs = "6.0.0"
colored = "3"
