[package]
name = "listener"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "listener"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
restore = { path = "../restore" }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
log = "0.4.28"